apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: quiz
type: Opaque
data:
  mongo-uri: bW9uZ29kYitzcnY6Ly9qb2t3dW9tYTpOZlZrbUN4cVRLU0dVdzlpQGNsdXN0ZXIwLmMwN3I0Lm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
  # my own encoded MongoDB connection string is shown above
  # mongo-uri: bW9uZ29kYitzcnY6Ly9xdWl6X3VzZXI6M1BiMHprZDZjMEFJWkVyRUBjbHVzdGVyMC4zeDBzN2hoLm1vbmdvZGIubmV0Lz9hcHBOYW1lPW1vbmdvc2grMi4xLjU=
  # mongo-uri listed above this line is prior user's encoded connecting string
